:init revision

 :Git

  : rev count
  FOR /F %%i IN ('git rev-list HEAD --count') DO set git_rev_count=%%i

  : rev SHA1 short
  FOR /F %%i IN ('git rev-parse --short HEAD') DO set git_rev_sha1=%%i

  : branch name
  FOR /F %%i IN ('git rev-parse --abbrev-ref HEAD') DO set git_branch_name=%%i

  
 : output
 set format_ident=r%git_rev_count%-%git_rev_sha1%
 
 cd src\reg\util\dc\flydcstat
 echo // generated by revision.bat > Version.java
 echo package reg.util.dc.flydcstat;>> Version.java
 echo public class Version>> Version.java
 echo {>> Version.java
 echo     public final static String specification = "0.2.3";>> Version.java
 echo     public final static String implementation = "";>> Version.java
 echo     public final static String revSha1 = "%format_ident%";>> Version.java
 echo }>> Version.java


